version: "3"
services:
  database:
    image: mysql:8
    ports: 
      - 3306:3306
    environment:
       - MYSQL_ROOT_PASSWORD=himanshu
       - MYSQL_DATABASE=custom
       - MYSQL_USER=admin
       - MYSQL_PASSWORD=himanshu
